input { beats { port => 5044 } }
filter {
  if [app][t] {
    date { match => ["[app][t]", "ISO8601"] target => "@timestamp" }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "tele-logs-%{+YYYY.MM.dd}"
  }
}
